export * from "./auth.table";
export * from "./comments.table";
export * from "./config.table";
export * from "./friend-links.table";
export * from "./media.table";
export * from "./obsidian-post-links.table";
export * from "./post-revisions.table";
export * from "./posts.table";
export * from "./search.table";
